name: Build and deploy Yew project
on: [push]
jobs:
  download:
    name: BUILD AND DEPLOY
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Cargo
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Download wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: "latest"
      - name: Install Trunk
        uses: jetli/trunk-action@v0.5.0
        with:
          version: "latest"

      # build steps
      - name: Install target
        run: rustup target add wasm32-unknown-unknown
      - name: Compile
        run: trunk build

      # deployment steps
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
